### ISSUE TITLE
flutter_mvideo_plugin 插件代码仓库里面没有这个目录

### ISSUE THREAD

**Issue by g1e2x87** [ViktSun/flutter_mvp#1]
pub get failed (66; Because flutter_mvp depends on flutter_mvideo_plugin from
path which doesn't exist (could not find package flutter_mvideo_plugin at
"../flutter_mvideo_plugin"), version solving failed.)

**Comment by ViktSun** [comment]
感谢Issue,当时我调试的时候把插件引入了本地了。你重新拉取代码或者你把 pubspec.yaml文件中 

  flutter_mvideo_plugin:
    path: ../flutter_mvideo_plugin

把上面这段代码注释掉，把下面代码打开

 flutter_mvideo_plugin:
    git:
      url: https://github.com/UrielSun/MVideoPlugin.git
